[project]
name = "naswa-apprenticeship-crawler"
version = "0.1.0"
description = "A small Scrapy crawler project for apprenticeship announcements."
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "scrapy",
    "beautifulsoup4 (>=4.15.0,<5.0.0)",
    "markdownify (>=1.2.3,<2.0.0)",
    "openai (>=2.44.0,<3.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
    "jsonschema (>=4.26.0,<5.0.0)",
    "requests (>=2.34.2,<3.0.0)"
]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
